# Generated by Django 2.2.1 on 2019-09-12 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('question', models.CharField(default=0, max_length=500, verbose_name='質問')),
                ('blue', models.CharField(default=0, max_length=500, verbose_name='回答1')),
                ('red', models.CharField(default=0, max_length=500, verbose_name='回答1')),
            ],
            options={
                'verbose_name': '2択データ',
                'verbose_name_plural': '2択データ',
            },
        ),
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='店名')),
                ('guru', models.IntegerField(default=0, verbose_name='ぐるなびAPI有無')),
                ('genle', models.CharField(max_length=50, verbose_name='ジャンル1')),
                ('genle2', models.CharField(default=0, max_length=50, verbose_name='ジャンル2')),
                ('genle3', models.CharField(default=0, max_length=50, verbose_name='ジャンル3')),
                ('distance', models.IntegerField(verbose_name='距離')),
                ('price_lunch', models.IntegerField(verbose_name='昼金額')),
                ('price_dinner', models.IntegerField(verbose_name='夜金額')),
                ('station', models.CharField(max_length=50, verbose_name='最寄り駅')),
                ('tabeloog', models.FloatField(verbose_name='ログ')),
                ('tabelog', models.FloatField(verbose_name='ログ修正値')),
                ('tel', models.CharField(default=0, max_length=50, verbose_name='電話番号')),
                ('score', models.FloatField(verbose_name='評価')),
                ('times', models.IntegerField(default=3, verbose_name='評価回数')),
                ('other', models.CharField(default=0, max_length=50, verbose_name='その他')),
                ('lat', models.FloatField(default=0, verbose_name='緯度')),
                ('lon', models.FloatField(default=0, verbose_name='経度')),
                ('url', models.CharField(default=0, max_length=300, verbose_name='URL')),
            ],
            options={
                'verbose_name': '飲食店データ',
                'verbose_name_plural': '飲食店データ',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('gender', models.IntegerField(choices=[(0, '男性'), (1, '女性')], verbose_name='性別')),
                ('email', models.CharField(default=0, max_length=200, verbose_name='email')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー情報データ',
                'verbose_name_plural': 'ユーザー情報データ',
            },
        ),
    ]
