# Generated by Django 2.2.1 on 2019-09-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iekari', '0002_scorelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorelog',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='iekari.Question', verbose_name='2択'),
        ),
        migrations.AddField(
            model_name='scorelog',
            name='questions',
            field=models.IntegerField(default=0, verbose_name='回答'),
        ),
    ]
