# Generated by Django 2.2.1 on 2019-09-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iekari', '0003_auto_20190913_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorelog',
            name='question',
        ),
        migrations.RemoveField(
            model_name='scorelog',
            name='questions',
        ),
    ]
