# Generated by Django 2.2.1 on 2019-09-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iekari', '0004_auto_20190913_0145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoreLog',
        ),
    ]
