# Generated by Django 2.2.1 on 2019-09-12 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iekari', '0005_delete_scorelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=4, verbose_name='評価')),
                ('time', models.IntegerField(default=18, verbose_name='入店時間')),
                ('num', models.IntegerField(default=2, verbose_name='人数')),
                ('wait', models.IntegerField(default=0, verbose_name='待ち時間')),
                ('text', models.CharField(default=0, max_length=10000, verbose_name='感想')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iekari.Profile', verbose_name='ユーザー情報')),
                ('rest', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='iekari.Rest', verbose_name='飲食店')),
            ],
            options={
                'verbose_name': '飲食店評価データ',
                'verbose_name_plural': '飲食店評価データ',
            },
        ),
    ]
