# Generated by Django 2.2.1 on 2019-09-12 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iekari', '0006_scorelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreQ',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('answer', models.IntegerField(default=0, verbose_name='回答')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iekari.Profile', verbose_name='ユーザー情報')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iekari.Question', verbose_name=' 2択データ')),
            ],
            options={
                'verbose_name': '2択回答データ\x08',
                'verbose_name_plural': '2択回答データ',
            },
        ),
    ]
