# Generated by Django 2.2.1 on 2019-09-13 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iekari', '0007_scoreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreq',
            name='rest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='iekari.Rest', verbose_name='飲食店データ'),
        ),
    ]
