# Generated by Django 2.2.1 on 2019-09-13 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iekari', '0008_scoreq_rest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreq',
            name='rest',
        ),
    ]
